### ISSUE TITLE
Known documentation issues and improvements checklist

### ISSUE THREAD

**Issue by stoodder** [stoodder/falconjs#9]
Just wanted to get an issue prepared with known issues/todos for the current docs.
### Styles
- [ ] Make responsive
### Header
- [ ] Add github star count
### Splash Page
- [ ] Add high-level beliefs to splash page
- [ ] Add architecture diagram
- [ ] Add brief examples
### Getting Started
- [x] Add architecture diagram
- [ ] Add zip download of each example
- [ ] Re-add jsFiddles
### View Docs
- [ ] Add 'About Views' to discus core topics Falcon.apply(), '$view', Falcon.View, and the 'view' binging.
### Blog
- [ ] Initial Blog Setup
- [ ] Blog Post featuring 0.10.0
### New Sections
- [ ] Add Configuration Documentation
### Tweaks
- [ ] Remove "I" from docs.
